name: CI

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: Create Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1243220
        env:
          CF_API_KEY: ${{ secrets.CURSE_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
